
random_redirect:
   pages: true

collections_dir: collections
collections:
   wiki:
      output: true
      permalink: /:collection/:name

# Front matter defaults, so you don't need to set layouts on every new page.
# As long as pages are in the correct folder, they'll automatically have the
# correct layout. You can override this via each page's front matter.
defaults:
   -
      scope:
         path: "" # an empty string here means all files in the project
         type: "pages"
      values:
         layout: "page" # all pages will have the page.html layout unless overridden
         permalink: "/:path/:basename"
   -
      scope:
         path: "" # an empty string here means all files in the project
         type: "posts"
      values:
         layout: "post"
   -
      scope:
         path: "_wiki" # all pages in the wiki folder
         type: "wiki"
      values:
         layout: "wiki"
